import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Header from '../modules/components/Header'
import Hero from '../modules/sections/Hero'
import About from '../modules/sections/About'
import WorkExperience from '../modules/sections/WorkExperience'
import Skills from '../modules/sections/Skills'
import Projects from '../modules/sections/Projects'
import ContactMe from '../modules/sections/ContactMe'
import { Experience, PageInfo, Project, Skill, Social } from '../typing'
import { fetchPageInfo } from '../utils/fetchPageInfo'
import { fetchExperiences } from '../utils/fetchExperiences'
import { fetchProjects } from '../utils/fetchProjects'
import { fetchSkills } from '../utils/fetchSkills'
import { fetchSocials } from '../utils/fetchSocials'

type Props = {
  pageInfo : PageInfo,
  experiences : Experience[],
  skills : Skill[],
  projects : Project[],
  socials : Social[],
}

const Home: NextPage<Props> = ({pageInfo, experiences, skills, projects, socials}) => {

  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll z-0 scrollbar-track-gray-400/20 scrollbar-thumb-amber-500 scrollbar-thin'>
      <Head>
        <title>Frederick Lopez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header 
        socials={socials}
      />

      {/* Hero */}
      <section id="hero" className='snap-start'>
        <Hero
          pageinfo={pageInfo}
        />
      </section>

      {/* About */}
      <section id="about" className='snap-center'>
        <About
           pageinfo={pageInfo}
        />
      </section>

      {/* Experience */}
      <section id="experience" className='snap-center'>
        <WorkExperience
          experiences={experiences}
        />
      </section>

      {/* Skills */}
      <section id="skills" className='snap-start'>
        <Skills 
          skills={skills}
        />
      </section>

      {/* Projects */}
      <section id="projects" className='snap-start'>
        <Projects
          projects={projects}
        />
      </section>

      {/* Contact Me */}
      <section id="contact" className='snap-start'>
        <ContactMe/>
      </section>

    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async (context) => {
  const pageInfo: PageInfo = await fetchPageInfo();
  const experiences: Experience[] = await fetchExperiences();
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();
  const socials: Social[] = await fetchSocials();

  return {
      props : {
        pageInfo,
        experiences,
        skills,
        projects,
        socials,
      }
  }
}