import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../modules/components/Header'
import Hero from '../modules/sections/Hero'
import About from '../modules/sections/About'
import WorkExperience from '../modules/sections/WorkExperience'
import Skills from '../modules/sections/Skills'
import Projects from '../modules/sections/Projects'
import ContactMe from '../modules/sections/ContactMe'

const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll z-0 scrollbar-track-gray-400/20 scrollbar-thumb-amber-500 scrollbar-thin'>
      <Head>
        <title>Frederick Lopez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Hero */}
      <section id="hero" className='snap-start'>
        <Hero/>
      </section>

      {/* About */}
      <section id="about" className='snap-center'>
        <About/>
      </section>

      {/* Experience */}
      <section id="experience" className='snap-center'>
        <WorkExperience/>
      </section>

      {/* Skills */}
      <section id="skills" className='snap-start'>
        <Skills/>
      </section>

      {/* Projects */}
      <section id="projects" className='snap-start'>
        <Projects/>
      </section>

      {/* Contact Me */}
      <section id="contact" className='snap-start'>
        <ContactMe/>
      </section>

    </div>
  )
}

export default Home
